spring:
  application:
    name: trustify-backend

  data:
    mongodb:
      uri: mongodb+srv://muhammadsuhaib2805:8c4Y3ES1UilAXrT1@trustify.nwckntf.mongodb.net/trustify?retryWrites=true&w=majority&appName=Trustify
      database: trustify
      auto-index-creation: true
      socket-timeout: 30000
      connection-timeout: 30000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 465
    username: muhammadsuhaib2805@gmail.com
    password: tkju guyf dglg vxfn  # app password only (never your real password)
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  publishable:
    key: ${STRIPE_PUBLISHABLE_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
  currency: PKR

file:
  upload-dir: uploads/listings

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
    com.trustify: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
